name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env
      run: |
        echo "DIR=." >> $GITHUB_ENV
        echo "ROOT_PASSWORD=npm" >> $GITHUB_ENV
        echo "NPM_PASSWORD=npm" >> $GITHUB_ENV

    - name: Create networks
      run: docker network create -d bridge proxy

    - name: Start docker containers
      run: docker compose up --wait --wait-timeout 120 --detach

    - name: Show containers
      run: docker container ps

    - name: Networks
      run: docker network ls

    - name: Curl nginx
      run: |
        curl 0.0.0.0:8080 > curl_nginx_8080_result
        cat curl_nginx_8080_result
        curl 0.0.0.0:81 > curl_nginx_81_result
        cat curl_nginx_81_result

  proxy:
    name: Proxy
    needs: deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Homar-Docker
        run: git clone https://github.com/jmrenier13/Homarr-Docker

      - name: Set env
        run: |
          echo "DIR=./tests/nginx" >> $GITHUB_ENV
          echo "ROOT_PASSWORD=npm" >> $GITHUB_ENV
          echo "NPM_PASSWORD=npm" >> $GITHUB_ENV

      - name: Create networks
        run: |
          docker network create -d bridge proxy

      - name: Start docker containers
        run: |
          docker compose --file ./Homarr-Docker/docker-compose.yml --env-file ./tests/homarr.env up --wait --wait-timeout 120 --detach
          docker compose up --wait --wait-timeout 120 --detach

      - name: Show containers
        run: docker container ps

      - name: Networks
        run: docker network ls

      - name: Append hosts
        run: |
          sudo echo "127.0.0.1  homarr.example.local" | sudo tee -a /etc/hosts
          echo "$(</etc/hosts)"

      - name: Check IP
        run: nslookup homarr.example.local

      - name: Curl homarr directly
        run: |
          curl 0.0.0.0:7575 > curl_direct_result
          cat curl_direct_result

      - name: Curl homarr proxy
        run: |
          curl homarr.example.local > curl_proxy_result
          cat curl_proxy_result

      - name: Check if different
        run: cmp curl_direct_result curl_proxy_result || exit 1
